### ISSUE TITLE
I doubt if gc() really working 

### ISSUE THREAD

**Issue by codingindian** [slimdestro/Dual-Session-Logger-PHP-SlimDestro#1]
I have no way to figure out if gc inside packaged one really cleaning 

`$this->db->prepare("DELETE FROM {$this->dual_sessions_table} WHERE timestamp < :oldTimestamp");
`

**Comment by codingindian** [comment]
You can query table "dual_sessions_table" (or custom table if you have configured) to see if it's removing row when unset session key

**Comment by codingindian** [comment]
Closed

**Comment by mukul-kumar-mishra** [comment]
You can query table "dual_sessions_table" (or custom table if you have configured) to see if it's removing row when unset session key
